---

- name: Add user with specified privligies
  hosts: aruba
  gather_facts: false
  vars:
    user: ""
    privlege: ""
    password: ""
  
  tasks:
  - name: add james
    aruba_config:
      lines: password {{ privlege }} user-name {{ user }} plaintext {{ password }}
