---

- name: Add user with specified priviliges
  hosts: aruba
  gather_facts: false
  vars:
    user: "charlestest"
    privilege: "operator"
    password: "aruba123"

  tasks:

  - aruba_config:
      lines: password {{ privilege }} user-name {{ user }} plaintext {{ password }}
      save_when: always
