---

- name: Apply generated config file to device
  hosts: 

  tasks:

    - aruba_config:
        src: "{{ config_path }}/{{ inventory_hostname }}.cfg"
        match: none
        save_when: always
