---

- name: Upgrade ArubaOS image
  hosts: arubaoss

  vars:
    system_image_filename: "ios-123-123.bin"
    tftp_server: "10.5.41.10"

  tasks:

    - name: Save running config first
      aruba_config:
        save_when: always

    - name: Set boot file for secondary image, and reboot
      aruba_config:
        lines:
          - 'copy flash tftp {{ tftp_server }} {{ system_image_filename }}'
        prompt:
          - confirm
        answers:
          - "y"

    - name: Set boot file for secondary image, and reboot
      aruba_config:
        lines:
          - "boot system flash secondary"
        prompt:
          - confirm
        answers:
          - "y"

    - name: Set boot file for primary image, and reboot
      aruba_config:
        lines:
          - "boot system flash primary"
        prompt:
          - confirm
        answers:
          - "y"