---
  - name: Generate Aruba config from Jinja2
    hosts: localhost
    gather_facts: no
    tasks:
      - name: Create Configs Directory
        file: path=configs state=directory

  - name: Generate Aruba config from Jinja2
    hosts: aruba
    gather_facts: no
    tasks:
      - name: Generate Aruba Basic Config
        template:
          src: "{{ template_path }}/aruba_wireless.j2"
          dest: "{{ config_path }}/{{ inventory_hostname }}.cfg"
        delegate_to: localhost
