---

- name: Enrolling Aruba Switches into Central
  hosts: aruba
  gather_facts: false

  tasks:

    - name: Force switches to check in
      aruba_config:
        lines:
          - activate provision disable          