---

- name: Enrolling Aruba Switches into Central
  hosts: bchms
  gather_facts: false

  tasks:

    - name: Force switches to check in
      aruba_config:
        lines:
          - activate provision disable     
          - aruba-central-disable
          - activate software-update disable
      save_when: always     