---

- hosts: switch1 

  tasks:
    - name: Add config from generated template
      aruba_config:
        src: "{{ config_path }}/{{ inventory_hostname }}.cfg"
        match: none
        save_when: always
