---

- name: Disable Aruba Activate
  hosts: 
  gather_facts: false

  tasks:

    - name: Disable Aruba Activate
      aruba_config:
        lines:
          - activate provision disable
          - aruba-central-disable
          - activate software-update disable
        save_when: always