---

- name: Enrolling Aruba Switches into Central
  hosts: 
  gather_facts: false

  tasks:

    - name: Enable Aruba Activate
      aruba_config:
        lines:
          - activate provision enable
          - aruba-central enable
          - activate software-update enable
        save_when: always