---

- name: Find mac address in sec-switches
  hosts: fmes
  gather_facts: false
  connection: local

  vars_prompt:
     - name: mac
       prompt: What is the mac address?
       private: no

  tasks:
    - name: debugging
      ansible.builtin.debug:
        msg: 'Searching for {{ mac }}'

    - name: search
      aruba_command:
        commands:
          - "show mac-address | include {{ mac }}"
      register: printout

### NOT WORKING FROM HERE BELOW, TOO LAZY RN TO TROUBLESHOOT


    - set_fact:
        intf: |
          {{printout.stdout_lines[0] |
            map('regex_replace','^(?:[^ ]*\ ){6}([^ ]*) | (\w+$)') |
            list }}

#    - name: show int desc
#      aruba_command:
#        commands:
#          - "sh interfaces | inc {{ intf[0].strip() }}"
#      register: printout2

    - name: View output
      debug:
        msg: " {{ inventory_hostname}}  {{ intf[0].strip() }} "
