---

  - name: Generate Aruba config from Jinja2
    hosts: 
    gather_facts: no

    tasks:
    
      - name: Generate Aruba Basic Config
        template:
          src: "{{ template_path }}/aruba_oss_router.j2"
          dest: "{{ config_path }}/{{ inventory_hostname }}.cfg"
        delegate_to: localhost
