---

- name: Retrieve port errors on device
  hosts: bchms
  gather_facts: false
  vars:
    date: "{{ lookup('pipe','date +%Y-%m-%d') }}"
    
  tasks:

    - name: Create backup directory using today's date
      file:
        path: "{{ log_path }}/{{ date }}"
        state: directory

    - name: ArubaOSS
      aruba_command:
        commands:
          - sh int
      when: ansible_network_os == "aruba"
      register: errors

    - name: Export errors to logs
      copy:
        content: "{{ errors.stdout[0] }}"
        dest: "{{ log_path }}/{{ date }}/{{ inventory_hostname }}_errors.txt"