---

- name: Install AD Roles and Features
  hosts: 
  vars:

  tasks:

    - name: Install DHCP
      win_feature:
        name: DHCP
        state: present
        include_management_tools: true
        include_sub_features: true
      register: dhcp_install

    - name: Reboot when Feature and Roles requires it
      win_reboot:
      when: dhcp_install.reboot_required
