---

- name: Creating Directory
  hosts: localhost
  gather_facts: false
  vars:
    date: "{{ lookup('pipe','date +%Y-%m-%d') }}"

  tasks:

    - name: Create backup directory using today's date
      file:
        path: "{{ backup_path }}/{{ date }}"
        state: directory

- name: Backup Config
  hosts: firewalls
  connection: local
  vars:
    date: "{{ lookup('pipe','date +%Y-%m-%d') }}"

  tasks:

  - name: Get backup
    paloaltonetworks.panos.panos_export:
      provider: "{{ provider }}"
      category: "configuration"
      filename: "{{ backup_path }}/{{ date }}/{{ inventory_hostname }}-running-config.xml"
      create_directory: true
