---

- name: Create address group
  hosts: firewalls
  connection: local
  vars:
    provider:
      username: "{{ username }}"
      password: "{{ password }}"
#      api_key: ""
      ip_address: "{{ ip_address }}"

  tasks:

  - name: Create address group
    paloaltonetworks.panos.panos_address_group:
      provider: '{{ provider }}'
      name: 'Group'
      static_value: ['Address1', 'Address2']
      state: 'present'
