---

- name: Get a list of security policies
  hosts: PA-NORTH
  connection: local

  tasks:

  - name: Get rules
    paloaltonetworks.panos.panos_nat_rule:
      provider: '{{ provider }}'
      state: "gathered"
      gathered_filter: "*"
    register: nat

#  - debug:
#      msg: "{{ nat }}"

  - name: Save security policies to json gathered_file 
    copy:
      content: "{{ nat | to_nice_json }}"
      dest: "{{ log_path }}/{{ inventory_hostname }}_nat_rules.json"
    delegate_to: localhost

