---

- name: Get a list of security policies
  hosts: FIREWALL
  connection: local

  tasks:

  - name: Get rules
    paloaltonetworks.panos.panos_security_rule:
      provider: '{{ provider }}'
      state: "gathered"
      gathered_filter: "*"
    register: policies

  - debug:
      msg: "{{ policies }}"

