---

- name: Populating address group
  hosts: PA-SOUTH
  connection: local

  tasks:

  - name: Import list
    read_csv:
      path: "{{ source_files }}/address_list.csv"
    register: address_list
    delegate_to: localhost

  - name: Create address objects
    paloaltonetworks.panos.panos_address_object:
      provider: '{{ provider }}'
      name: '{{ item.name }}'
      address_type: "{{ item.type }}"
      value: '{{ item.address }}'
      state: "{{ item.state }}"
    loop: "{{ address_list.list }}"

  - name: Create address group from objects
    paloaltonetworks.panos.panos_address_group:
      provider: "{{ provider }}"
      name: "{{ item.group_name }}"
      static_value: "{{ item.name }}"
      state: "{{ item.group_state }}"
    loop: "{{ address_list.list }}"

  - name: Commit changes
    paloaltonetworks.panos.panos_commit_firewall:
      provider: '{{ provider }}'
      admins: ['cvincent']
      description: 'ansible test -cv'
