---

all:
  hosts:
   children:
     FW:
       PA-01:
         ansible_host: 1.1.1.1
       PA-02:
         ansible_host: 2.2.2.2
     home:
       home-cx6300-mdf01:
         ansible_host: 10.1.1.100
         ansible_user: admin
         ansible_password: password
         ansible_network_os: arubanetworks.aoscx.aoscx
         ansible_connection: arubanetworks.aoscx.aoscx   # or network_cli
         ansible_httpapi_use_ssl: True                   # only necessary when using REST api as it uses port 443
         ansible_aoscx_validate_certs: False
         ansible_aoscx_use_proxy: False
       mes-cx6300-idf01:
         ansible_host: 10.1.1.101
         ansible_user: admin
         ansible_password: password
         ansible_network_os: arubanetworks.aoscx.aoscx
         ansible_connection: arubanetworks.aoscx.aoscx   # or network_cli
         ansible_httpapi_use_ssl: True                   # only necessary when using REST api as it uses port 443
         ansible_aoscx_validate_certs: False
         ansible_aoscx_use_proxy: False
