# docker-compose.yml
# use "docker-compose up -d && docker-compose logs -f" to start checkmk with an output to see login creds

version: '3.6'

services:
  checkmk:
    container_name: checkmk
    image: checkmk/check-mk-raw:2.2.0-latest
    tmpfs:
      - /opt/omd/sites/cmk/tmp:uid=1000,gid=1000
    ulimits:
      nofile: 1024
    volumes:
      - ./monitoring:/omd/sites
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8080:5000"
    restart: unless-stopped
    env_file:
      - .env
    networks:
      checkmk_network:

networks:
    checkmk_network: