---

- hosts: 

  tasks:

    - name: Apply generated config file to device
      ios_config:
        src: "{{ config_path }}/{{ inventory_hostname }}.cfg"
        match: none
        save_when: always
      when: ansible_network_os == "ios"
