---

- name: Create directory for ARP table export
  hosts: localhost
  gather_facts: false
  vars:
    date: "{{ lookup('pipe','date +%Y-%m-%d') }}"

  tasks:

    - name: Create logging directory using today's date
      file:
        path: "/etc/ansible/logs/{{ date }}"
        state: directory

- name: Export ARP table for iOS
  hosts: routers:&ios
  gather_facts: false
  vars:
    date: "{{ lookup('pipe','date +%Y-%m-%d') }}"

  tasks:

    - name: iOS
      ios_command:
        commands: sh arp
      when: ansible_network_os == "ios"
      register: results

    - name: output
      debug:
        var: results

    - name: Export ARP table
      copy:
        # content: "{{ results.stdout | replace('\\n', '\n') }}"
        content: |
          IP Address,MAC Address
          {% for line in results.stdout[0].split('\n')[1:] %}
          {% set parts = line.split() %}
          {% if parts | length >= 4 and parts[3] != 'Incomplete' %}
          {% set raw_mac = parts[3].replace('.', '') %}
          {% set norm_mac = raw_mac[0:2] ~ ':' ~ raw_mac[2:4] ~ ':' ~ raw_mac[4:6] ~ ':' ~ raw_mac[6:8] ~ ':' ~ raw_mac[8:10] ~ ':' ~ raw_mac[10:12] %}
          {{ parts[1] }},{{ norm_mac }}
          {% endif %}
          {% endfor %}
        dest: "/etc/ansible/logs/{{ date }}/{{ inventory_hostname }}_arp.csv"