---

- name: Upgrade IOS image
  hosts: ios
  gather_facts: false

  vars:
    system-image-filename: "ios-123-123.bin"

  tasks:

    - name: Save running config first
      ios_config:
        save_when: always


    - name: Copy image from control node to host
      net_put:
        src: /etc/ansible/images/{{ system-image-filename.bin }}"
        dest: "flash:/{{ system-image-filename.bin }}"
      vars:
        ansible_command_timeout: 600
        

    - name: Set boot file
      ios_config:
        commands:
          - "boot system flash:{{ system-image-filename.bin }}"
        save_when: always

    - name: Reboot host
      ios_command:
        command: reload
        prompt:
          - confirm
        answer:
          - 'y'
