---

- name: Create multiple VLANs
  ios_vlan:
    config:
      - name: WAPs
        vlan_id: 100
      - name: VOIP
        vlan_id: 200
      - name: Cameras
        vlan_id: 300
    state: merged

#- name: Create VLAN 100
#  ios_vlan:
#    config:
#      - name: WAPs
#        vlan_id: 100
#        shutdown: disabled
#        state: active
#    state: merged



- name: Configure access ports
  ios_l2_interfaces:
    config:
      -  name: FastEthernet0/1
         access:
          vlan: 100
    state: merged

- name: Configure trunk port
  ios_l2_interfaces:
    config:
      -  name: GigabitEthernet0/1
         trunk:
          allowed_vlans: 100-300
          encapsulation: dot1q
          native_vlan: 1
    state: merged
