---

- name: Remove incorrect NTP servers
  hosts: 
  gather_facts: false

  tasks:

    - name: Remove the trash from Josh
      aruba_config:
        lines:
          - no ntp server 216.239.35.4 iburst
          - no ntp server 216.239.35.8 iburst
          - no ntp server 216.239.35.4
          - no ntp server 216.239.35.8


- name: Correct NTP servers
  hosts: north
  gather_facts: false

  tasks:

    - name: Add appropriate NTP servers depending on side of district
      aruba_config:
        lines:
          - ntp server 10.8.0.120 iburst
          - ntp server 10.8.0.121 iburst


- name: Correct NTP servers
  hosts: south
  gather_facts: false

  tasks:

    - name: Add appropriate NTP servers depending on side of district
      aruba_config:
        lines:
          - ntp server 10.101.0.10 iburst
          - ntp server 10.101.0.11 iburst


- name: Save configs
  hosts: arubaoss
  gather_facts: false

  tasks:

    - name: Remove the trash from Josh
      aruba_command:
        lines:
          - write memory
        
