---

- hosts: CENTRAL
  collections:
    - arubanetworks.aruba_central

  tasks:

  - name: Create a new group
    central_groups:
      action: create
      group_name: Ansible_Test
      group_attributes:
        group_password: password
        template_group:
          wired: false
          wireless: false

#  - name: Move devices into the group
#    central_devices:
#      action: move_devices
#      group_name: new-group
#      device_serial_list:
#         - CNXXXXXXXX
#         - CNXXXXXXYY
