---
  - name: Generate Aruba config from Jinja2
    hosts: localhost
    gather_facts: no
    tasks:
      - name: Create Configs Directory
        file: path=configs state=directory

  - name: Generate Aruba config from Jinja2
    hosts: Aruba
    gather_facts: no
    tasks:
      - name: Generate Aruba Basic Config
        template:
          src: "./templates/aruba.j2"
          dest: "./configs/{{inventory_hostname}}.cfg"
        delegate_to: localhost
