---

- name: Retrieve port errors on device
  hosts: 
  gather_facts: false
  vars:
    date: "{{ lookup('pipe','date +%Y-%m-%d') }}"
    
  tasks:

    - name: Create backup directory using today's date
      file:
        path: "/etc/ansible/logs/{{ date }}"
        state: directory

    - name: iOS
      ios_command:
        commands:
          - sh int cou err
      when: ansible_network_os == "ios"
      register: errors
    
    - name: ArubaOSS
      aruba_command:
        commands:
          - sh int
      when: ansible_network_os == "aruba"
      register: errors

    - name: Export errors to logs
      copy:
        content: "{{ errors.stdout[0] }}"
        dest: "/etc/ansible/logs/{{ date }}/{{ inventory_hostname }}_errors.txt"