---

- hosts: CENTRAL
  collections:
    - arubanetworks.aruba_central

  tasks:

  - name: Create a new group
    central_groups:
      action: create
      group_name: Ansible_Test
      group_attributes:
        group_password: Bryan1q2w3e!Q@W#E
        template_group:
          wired: false
          wireless: false

#  - name: Upload a template for created group of devices
#    central_templates:
#      action: create
#      group_name: new-group
#      template_name: aos-sw-temp
#      device_type: ArubaSwitch
#      version: ALL
#      model: ALL
#      local_file_path: /home/admin/sw_template.txt

#  - name: Set template variables for all/multiple devices using a JSON file
#    central_variables:
#      action: create_all
#      local_file_path: /home/admin/variables.json

#  - name: Move devices into the group
#    central_devices:
#      action: move_devices
#      group_name: new-group
#      device_serial_list:
#         - CNXXXXXXXX
#         - CNXXXXXXYY
