---

- name: Upgrade Windows Servers
  hosts: 
  vars:

  tasks:

    - name: Check for updates
      win_updates:
        category_names:
          - SecuirtyUpdates
          - CriticalUpdates
          - UpdateRollups
        state: searched
        log_path: /Temp/update.txt