---

- name: Reboot machines like a psycho
  hosts: test
  vars:

  tasks:

#    - name: Reboot host(s)
#      win_reboot:
#      when: update_result.reboot_required

    - name: Send Teams message when reboot is required
      uri:
        url: "{{ teams_webhook_url }}"
        method:  POST
        body_format: json
        body:
          title: "Ansible Alert"
          text: "{{ inventory_hostname }} has been rebooted."
      delegate_to: 127.0.0.1
