---

- name: Upgrade Windows Servers
  hosts: test
  vars:

  tasks:

    - name: Upgrade
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
        state: installed
        log_path: /Temp/update.txt
      register: update_result

    - name: Reboot host if required
      win_reboot:
      when: update_result.reboot_required

    - name: Send Teams message when reboot is required
      uri:
        url: "{{ teams_webhook_url }}"
        method:  POST
        body_format: json
        body:
          title: "Ansible Alert"
          text: "{{ inventory_hostname }} has been updated and will now reboot."
      delegate_to: 127.0.0.1