---

- name: Backup running config of network devices
  hosts: localhost
  gather_facts: false
  vars:
    date: "{{ lookup('pipe','date +%Y-%m-%d') }}"

  tasks:

    - name: Create backup directory using today's date
      file:
        path: "/etc/ansible/backups/{{ date }}"
        state: directory

- name: Backup running config of network devices
  hosts: 
  gather_facts: false
  vars:
    date: "{{ lookup('pipe','date +%Y-%m-%d') }}"

  tasks:

    - name: Backup Cisco configuration to /etc/ansible/backups/
      ios_config:
        backup: yes
        backup_options:
          filename:  "{{ inventory_hostname }}-{{ date }}.txt"
          dir_path: "/etc/ansible/backups/{{ date  }}"
      when: ansible_network_os == "ios"

    - name: Backup Aruba configuration to /etc/ansible/backups/
      aruba_config:
        backup: yes
        backup_options:
          filename:  "{{ inventory_hostname }}-{{ date }}.txt"
          dir_path: "/etc/ansible/backups/{{ date }}"
      when: ansible_network_os == "aruba"