---

- name: Backup running config of Cisco device
  hosts: routers
  gather_facts: false

  tasks:
    - name: Show running configuration of device
      ios_command:
        commands: show run
      register: show_run

    - name: Copy configuration to /etc/ansible/backups/
      copy:
        content: "{{ show_run.stdout[0] }}"
        dest: "/etc/ansible/backups/{{ inventory_hostname }}.txt"
