---

- name: Backup running config of Cisco device
  hosts: alwayson
  gather_facts: false
  vars:
    date: "{{ lookup('pipe','date +%Y-%m-%d') }}"

  tasks:

    - name: Create backup directory using today's date
      file:
        path: "/etc/ansible/backups/{{ date }}"
        state: directory


    - name: Backup configuration to /etc/ansible/backups/
      ios_config:
        backup: yes
        backup_options:
          filename:  "{{ inventory_hostname }}.txt"
          dir_path: "/etc/ansible/backups/{{ date }}/"
