---

- Name: Backup running config of Cisco device
  hosts: ios
  connection: network_cli
  gather_facts: false

  vars:
    creds:
      username: "{{ username }}"
      password: "{{ password }}"

  tasks:
    - Name: Show Run
      ios_command:
        provider: "{{ creds }}"
        commands: show run
      register: show_run

    - Name: Backup to server
      copy:
        content: "{{ show_run.stdout[0] }}"
        dest: "/etc/ansible/backups/{{ hostvars.localhost.DTG }}/{{ inventory_hostname }}.txt"
