---

- name: Retrieve port errors on device
  hosts: sandbox-iosxe-latest-1.cisco.com
  gather_facts: false
  vars:
    date: "{{ lookup('pipe','date +%Y-%m-%d') }}"
    
  tasks:

    - name: Create backup directory using today's date
      file:
        path: "/etc/ansible/logs/{{ date }}"
        state: directory


    - name: Get int status
      cisco.ios.ios_command:
        commands:
          - sh int cou err
      register: errors
    
    - name: Export errors to logs
      ansible.builtin.copy:
        content: "{{ errors.stdout[0] }}"
        dest: "/etc/ansible/logs/{{ date }}/{{ inventory_hostname }}_errors.txt"





