---

- name: Upgrade IOS image
  hosts: ios
  gather_facts: false

  vars:
    system-image-filename: "ios-123-123.bin"

  tasks:
    - name: Copy image from control node to host
      command: "scp {{ system-image-filename.bin }} {{ inventory_hostname }}:/{{ system-image-filename.bin }}"

    - name: Set boot file
      ios_config:
        commands:
          - "boot system flash:{{ system-image-filename.bin }}"

    - name: Reboot host
      ios_command:
        commands:
          - reload\n"
