---

- name: Configure Banner MOTD
  hosts: ios
  connection: network_cli
  gather_facts: false

  vars:
    creds:
      username: "{{ username }}"
      password: "{{ password }}"

  tasks:
    - name: Configure Banner MOTD
      ios_config:
        provider: "{{ creds }}"
        lines:
          - banner motd $ Keep Out $
