---

- name: Replace a word in all files in a folder
  hosts: localhost

  tasks:

    - name: Find all files in the target folder
      ansible.builtin.find:
        paths: "$HOME/ansible/configs/rhhs"
        file_type: file
      register: found_files

    # - name: Replace vlan in each file
    #   ansible.builtin.replace:
    #     path: "{{ item.path }}"
    #     regexp: "{{ old_vlan }}"
    #     replace: "{{ new_vlan }}"
    #   loop: "{{ found_files.files }}"
    #   vars:
    #     old_vlan: "128"
    #     new_vlan: "127"

    - name: Replace vlan name in each file
      ansible.builtin.replace:
        path: "{{ item.path }}"
        regexp: "{{ old_text }}"
        replace: "{{ new_text }}"
      loop: "{{ found_files.files }}"
      vars:
        old_text: "Neo"
        new_text: ""
