---

- Charles:
    username: charles
    password: 'cisco123'
    privilege: '15'

- Josh:
    username: josh
    password: 'cisco456'
    privilege: '15'

- Bob:
    username: robert
    password: 'cisco789'
    privilege: '15'
